<?php

return [
    'reports' => 'Reports',
    'total_shops' => 'Total Shops',
    'total_billed' => 'Total Billed',
    'total_collected' => 'Total Collected',
    'total_due' => 'Total Due',

    'collection_report' => 'Collection Report',
    'collection_report_desc' => 'Payments collected by date range.',
    'due_report' => 'Due Report',
    'due_report_desc' => 'Outstanding dues by shop.',
    'shop_report' => 'Shop Report',
    'shop_report_desc' => 'Complete shop listing with status.',
    'monthly_summary' => 'Monthly Summary',
    'monthly_summary_desc' => 'Monthly overview of billing and collection.',
    'staff_performance' => 'Staff Performance',
    'staff_performance_desc' => 'Collection performance by staff.',
    'invoice_report' => 'Invoice Report',
    'invoice_report_desc' => 'All invoices for a billing month.',

    'from_date' => 'From Date',
    'to_date' => 'To Date',
    'filter_by' => 'Filter By',
    'all_dues' => 'All Dues',
    'overdue_only' => 'Overdue Only',
    'pending_only' => 'Pending Only',
    'shop_status' => 'Shop Status',
    'select_month' => 'Select Month',
    'billing_month' => 'Billing Month',

    'recent_reports' => 'Recent Generated Reports',
    'report_type' => 'Report Type',
    'generated_at' => 'Generated At',
    'generated_by' => 'Generated By',

    // Keys used by the Blade views
    'total_invoices' => 'Total Invoices',
    'total_rent' => 'Total Rent',
];
